### ISSUE TITLE
`idris-mode` in Emacs doesn't see packages I depend on through elba.

### ISSUE THREAD

**Issue by NobbZ** [elba/elba#43] opened 2019-03-20 08:53 UTC
Due to this also the started Idris process doesn't see them, and I can not split on anything coming from an external package, also Emacs will fail to load and understand the file at all as soon as I use something from a package I depend on.

This makes Elba pretty useless. Is there a way to convince Emacs/the Idris started by Emacs to use the proper dependencies?

**Comment by andylokandy** [comment] 2019-03-20 09:32
This is a known issue been disscuesed in https://github.com/elba/elba/issues/3. The discussion result is to expose built dependencies in `target/deps` and let the pluggins of `Vim`, `Emacs`, `VSCode` and so on to include it.

**Comment by NobbZ** [comment] 2019-03-20 10:32
Is this documented somewhere better than just hidden in that issue? Even though you pointed at it, its hard to find this information burried in there as it is in a lot of noise.

Also, I am unable to find a setting for `idris-mode` that I could use to specify a package path, can you point me to some documentation about this, or shall I ask at the `idris-mode` bug tracker?

In general, a small guide that explains how to use `elba` with the most common editors for idris would be nice.

**Comment by NobbZ** [comment] 2019-03-20 10:46
As a sidenote, I opened idris-hackers/idris-mode#497, to ask about hints with the package load path.

**Comment by andylokandy** [comment] 2019-03-20 14:28
Thanks for bring this up! It has not been documented because it's not totally implemented, that's why I called it an issue. This should be our goal in 0.3 milestone, but for some reason it seems not, @dcao did you miss this?

**Comment by andylokandy** [comment] 2019-03-20 14:33
As I remembered, this can not be achieved only by plugins, but also by compiler, because the compiler does not provide proper command line interface to specify an include path in query mode.

**Comment by andylokandy** [comment] 2019-03-20 14:38
As I am working heavliy on the website backend of elba now (https://github.com/elba/website), I'll take over this after that, or @dcao may have time to handle this.

**Comment by andylokandy** [comment] 2019-04-12 08:21
Is there a plan on this or is it actually implemented? I can help solving this issue now.

**Comment by dcao** [comment] 2019-04-14 02:28
There isn't a plan on how to resolve this at the moment.

The problem is that during building, elba doesn't actually copy all the dependencies to a `target/deps` folder (I'm pretty sure); the solution to this issue would probably mean providing a list of package directories to any editor plugins manually (possibly via an extra subcommand or something).

**Comment by andylokandy** [comment] 2019-04-14 04:36
Maybe we can generate an dependency specification file? I'll dive in the plugins to see how can this work. But I'm still open to the target/deps solution. also a build dependency only command like npm have should be useful in plugin aspect. A minimum interface like `elba build --only-deps ` should work.

**Comment by andylokandy** [comment] 2019-04-16 16:30
`idris -i PATH --ide-mode` seems working great, so it means that we just need to let plugin add those import path on startup. I propose to create a `target/.deps` file after elba finished the typecheck phase and then the plugins can watch this file and reload it when it get changed.

**Comment by dcao** [comment] 2019-04-16 17:13
Actually, I've already implemented `elba repl --ide-mode`, which builds all dependencies and automatically loads them for use in the ide-mode. (It also cleans up any stray ibc files in the directory once it closes). I could implement `elba repl --ide-mode-socket` and instead of having editor plugins watch the `target/deps` file along with the manifest file for changes, they could just watch the manifest file and re-run `elba repl --ide-mode-socket` or `elba repl --ide-mode`.

**Comment by andylokandy** [comment] 2019-04-16 19:00
Good approach! One concern here: whether elba locks the dir on ide-mode? The plugins usually hold a compiler running in background during time

**Comment by dcao** [comment] 2019-04-17 04:58
In ide-mode, elba doesn't lock the directory, so an `elba build` invocation could run simultaneously to an `elba repl` invocation.

At this point, the onus falls on editor plugins to support elba. The general steps needed for an editor plugin to do this is pretty simple:

1. If an elba manifest/lock file is detected, switch from using `idris --build`/`idris --ide-mode`/etc. to `elba build`/`elba repl --ide-mode`/etc.

2. Watch for changes in the lockfile; on a change, kill any ide servers and restart them.

If there aren't any concerns with this issue on elba's side of things, I'm going to go ahead and close this issue.

**Closed** 2019-04-17 05:00 UTC
Labels: enhancement

**Comment by andylokandy** [comment] 2019-04-17 11:36
Why can't we just use `elba repl -- --ide-mode`? And I wonder why this is not working for now.

**Comment by andylokandy** [comment] 2019-04-19 09:40
@NobbZ I've implemented an experimental solution here: https://github.com/elba/idirs-elba-interface. It has been tested on vscode, you can give it a try on emcas to see if there is any problem.
